### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by carrieroent** [nlarche/qobuz-desktop-player#6]
@nlarche, as far I know wrapping a web app into an Electron app is pretty trivial/easy, can you update this to work again? I don't know how do it and I really need this.

Note: I understand if you don't have time for this; this is just a request and if you don't have time I hope you can tell it.

**Comment by nlarche** [comment]
Hi @carrieroent, I currently don't have time for this. so feel free to make a PR or look at the forks.
